### ISSUE TITLE
I get two versions of the same exceptions

### ISSUE THREAD

**Issue by andreip** [eventlet/eventlet#442]
Hi,

I've stumbled into a problem in my application code, but first here's the minimalist way I was able to reproduce it; something similar happens in my app code and I end up with two versions of the same exception:

```bash
$ python
Python 3.6.1 (default, Jun 12 2017, 11:04:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> from urllib.error import URLError
>>> urllib.error.URLError == URLError
True
>>> import eventlet.green.urllib.error
>>> urllib.error.URLError == URLError
False
```

Is this behavior known / expected?

In my app, I was unaware of the import difference so I just did `from urllib.error import URLError` and then used that inside a try/except around a feedparser call that internally uses urllib and from time to time `urllib/request.py` raises a `URLError`, but my catch branch wouldn't get called due to these exceptions being different.

It was really weird and quite hard to find the problem. As far as I understood, that happens because `patcher.inject('urllib.error', globals(), ('urllib.response', response))` from `eventlet.green.urllib.error` removes an already existing `sys.modules['urllib.error']` and adds another one, but not sure how changes are propagated back to me in the python prompt, since `patcher.inject()` seems to not produce any side effects, except for adding a new module with its globals changed with `__patched_module_` prefix in `sys.modules`, and for changing the globals of the calling module to contain those attributes of the newly imported module:

```python
>>> import urllib.error
>>> id(globals()['urllib'])
4390335176
>>> id(urllib.error)
4390335016
>>> id(globals()['urllib'].error)
4390335016
>>> import eventlet.green.urllib.error
>>> id(globals()['urllib'])
4390335176
# Don't understand the next two lines, how they got changed by above import
>>> id(urllib.error)
4409811416
>>> id(globals()['urllib'].error)
4409811416
>>> import sys
# Expected, since `saver.restore()` brings it back
>>> id(sys.modules['urllib.error'])
4390335016
```

**Comment by temoto** [comment]
Hello, thank you for report. We have similar problem (partly) fixed in green subprocess #413 , probably in more modules. I'll see if quick fix is possible.

**Comment by temoto** [comment]
@andreip  In the meantime, please try workaround and tell if it helps with your code.

```diff
-from module import name
+import module

-except name:
+except module.name:
```

Importing names + monkey patching is a sure way to get headache.

**Comment by andreip** [comment]
@temoto yep I did that already as a workaround in my app and it works fine (`import urllib; ... except urllib.error.URLError`), thanks for your quick response!

**Comment by temoto** [comment]
@andreip if possible please also try old code with this patch.

`pip install https://github.com/eventlet/eventlet/archive/0c416976201ffd7adc48a71f105ea4dc2312f6b9.zip`

**Comment by andreip** [comment]
@temoto yes I can still reproduce it with the old code where I did `from urllib.error import URLError`. I checked the venv code and eventlet installed correctly from the zip you provided when I gave it an `--upgrade`.

And this it can still be reproduced by code I posted above:

```bash
$ python -c "import urllib; from urllib.error import URLError; print(urllib.error.URLError == URLError); import eventlet.green.urllib.error; print(urllib.error.URLError == URLError)"
True
False
```

**Comment by temoto** [comment]
Thanks.

**Comment by temoto** [comment]
Sorry for leaving this issue open.
